### ISSUE TITLE
Array vs Object

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [xgqfrms/learning#13]
https://stackoverflow.com/questions/4775722/check-if-object-is-array

**Comment by xgqfrms-GitHub** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/instanceof

**Comment by xgqfrms** [comment]
> instanceof 运算符用来测试一个对象在其原型链中是否存在一个构造函数的 prototype 属性。

```js
Array.isArray = Array.isArray || function (vArg) {
    return Object.prototype.toString.call(vArg) === "[object Array]";
};

```
